import XCTest
@testable import RayNotesCore

final class RayNotesCoreTests: XCTestCase {
    private var directory: URL!
    override func setUpWithError() throws { directory = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString); try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true) }
    override func tearDownWithError() throws { try? FileManager.default.removeItem(at: directory) }
    func testUnlimitedRestartUnicodeSearch() throws { let store = try NoteStore(directory: directory); for i in 0..<7 { var n = Note(title: "회의 \(i)", body: i == 6 ? "한글 참석자 홍길동" : "body"); n.updatedAt = Date(timeIntervalSince1970: TimeInterval(i)); try store.save(n) }; let restarted = try NoteStore(directory: directory); XCTAssertEqual(try restarted.all().count, 7); XCTAssertEqual(try restarted.search("홍길동").count, 1) }
    func testRoutesRejectBadIdentifiersAndDecodeQuery() throws { XCTAssertEqual(try RouteParser.parse(URL(string: "raynotes://search?q=%ED%9A%8C%EC%9D%98")!), .search("회의")); XCTAssertThrowsError(try RouteParser.parse(URL(string: "raynotes://open?id=bad")!)); XCTAssertThrowsError(try RouteParser.parse(URL(string: "other://new")!)) }
    func testFailureDoesNotChangeExistingDisk() throws { let store = try NoteStore(directory: directory); let note = Note(title: "before", body: "safe"); try store.save(note); try FileManager.default.setAttributes([.posixPermissions: 0o500], ofItemAtPath: directory.path); defer { try? FileManager.default.setAttributes([.posixPermissions: 0o700], ofItemAtPath: directory.path) }; var changed = note; changed.body = "lost"; XCTAssertThrowsError(try store.save(changed)); XCTAssertEqual(try store.load(note.id).body, "safe") }
    func testTrashRestoreAndBackupRecovery() throws { let store = try NoteStore(directory: directory); var note = Note(title: "keep", body: "old"); try store.save(note); note.body = "new"; try store.save(note); try store.trash(note.id); XCTAssertTrue(try store.all().isEmpty); try store.restore(note.id); XCTAssertEqual(try NoteStore(directory: directory).all().count, 1); let file = directory.appendingPathComponent(note.id.uuidString).appendingPathExtension("json"); try Data("broken".utf8).write(to: file); XCTAssertEqual(try store.load(note.id).body, "new") }
    func testRecoveredBackupIsNeverReplacedFromCorruptPrimary() throws { let store = try NoteStore(directory: directory); var note = Note(title: "safe", body: "backup body"); try store.save(note); note.body = "new primary"; try store.save(note); let primary = directory.appendingPathComponent(note.id.uuidString).appendingPathExtension("json"); let backup = directory.appendingPathComponent(note.id.uuidString).appendingPathExtension("json.bak"); let backupBefore = try Data(contentsOf: backup); try Data("corrupt".utf8).write(to: primary); var recovered = try store.load(note.id); recovered.body = "attempt"; XCTAssertThrowsError(try store.save(recovered)); XCTAssertEqual(try Data(contentsOf: backup), backupBefore); XCTAssertEqual(try store.load(note.id).body, "backup body") }
    func testExport() throws { let store = try NoteStore(directory: directory); let note = Note(title: "내보내기", body: "내용"); let out = directory.appendingPathComponent("out.md"); try store.export(note, to: out); XCTAssertTrue(try String(contentsOf: out).contains("내용")) }
    func testLegacyReadIsByteStableThenEditMigratesToMarkdown() throws { let id = UUID(); let legacy = "{\"id\":\"\(id.uuidString)\",\"title\":\"기존 제목\",\"body\":\"기존 본문\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"updatedAt\":\"2026-01-01T00:00:00Z\",\"isTrashed\":false,\"isPinned\":false}"; let file = directory.appendingPathComponent(id.uuidString).appendingPathExtension("json"); try Data(legacy.utf8).write(to: file); let before = try Data(contentsOf: file); let store = try NoteStore(directory: directory); var note = try store.load(id); XCTAssertEqual(note.editorMarkdown, "# 기존 제목\n\n기존 본문"); XCTAssertEqual(try Data(contentsOf: file), before); note.applyEditedMarkdown("# 바뀐 제목\n\n**한글**"); try store.save(note); let loaded = try store.load(id); XCTAssertTrue(loaded.isMarkdownDocument); XCTAssertEqual(loaded.title, "바뀐 제목"); let out = directory.appendingPathComponent("m.md"); try store.export(loaded, to: out); XCTAssertEqual(try String(contentsOf: out), "# 바뀐 제목\n\n**한글**") }
    func testExistingHeadingIsNotDuplicatedAndMissingHeadingIsSafe() throws { let legacy = Note(title: "무시", body: "# 이미 제목\n\n본문", formatVersion: nil); XCTAssertEqual(legacy.editorMarkdown, legacy.body); var markdown = Note(title: "x", body: "", formatVersion: nil); markdown.applyEditedMarkdown("질문만 적음"); XCTAssertEqual(markdown.title, "제목 없음"); XCTAssertEqual(markdown.body, "질문만 적음") }
    func testMarkdownContinuationAndChecklistRoundTrip() { XCTAssertEqual(MarkdownEditing.continuation(for: "  - [x] 완료"), "  - [ ] "); XCTAssertEqual(MarkdownEditing.continuation(for: "  9) 한국어"), "  10) "); XCTAssertEqual(MarkdownEditing.continuation(for: "- 항목"), "- "); XCTAssertEqual(MarkdownEditing.toggledChecklistLine("- [ ] 할 일"), "- [x] 할 일"); XCTAssertEqual(MarkdownEditing.toggledChecklistLine("- [x] 할 일"), "- [ ] 할 일") }
    func testEmptyMarkdownListItemsExitAndIndentedTasksToggle() { XCTAssertNil(MarkdownEditing.continuation(for: "- ")); XCTAssertNil(MarkdownEditing.continuation(for: "  - [ ] ")); XCTAssertNil(MarkdownEditing.continuation(for: "1. ")); XCTAssertEqual(MarkdownEditing.toggledChecklistLine("  - [ ] 유니코드 ✅"), "  - [x] 유니코드 ✅") }
    func testEmptyListExitKeepsOnlyIndentation() { XCTAssertEqual(MarkdownEditing.emptyListIndent(for: "- "), ""); XCTAssertEqual(MarkdownEditing.emptyListIndent(for: "  - [x] "), "  "); XCTAssertEqual(MarkdownEditing.emptyListIndent(for: "\t2. "), "\t"); XCTAssertNil(MarkdownEditing.emptyListIndent(for: "- 내용")) }
    func testFencedCodeStateUsesOnlyFenceLines() { XCTAssertFalse(MarkdownEditing.isInsideFencedCode(before: "# 제목\n\n- 항목")); XCTAssertTrue(MarkdownEditing.isInsideFencedCode(before: "```swift\n- code")); XCTAssertFalse(MarkdownEditing.isInsideFencedCode(before: "```\n- code\n```\n- 항목")); XCTAssertFalse(MarkdownEditing.isInsideFencedCode(before: "문장 안 ``` 표식")) }
    func testTabIndentEditsWholeListLineAndLeavesPlainTextAlone() { let document = "# 제목\n\n- 한글 항목\n  - [ ] 다음"; let caret = (document as NSString).range(of: "한글").location + 1; let edit = MarkdownEditing.listIndentEdit(document: document, selection: NSRange(location: caret, length: 0), outdent: false)!; XCTAssertEqual(edit.replacement, "  - 한글 항목\n"); XCTAssertEqual(edit.selection.location, caret + 2); XCTAssertNil(MarkdownEditing.listIndentEdit(document: "일반 문장", selection: NSRange(location: 0, length: 0), outdent: false)) }
    func testTabPreservesNextLineAndShiftTabRoundTripsMultipleEmojiLines() { let document = "- a\n- 😀 b\n- c"; let first = MarkdownEditing.listIndentEdit(document: document, selection: NSRange(location: 1, length: 0), outdent: false)!; let afterFirst = (document as NSString).replacingCharacters(in: first.range, with: first.replacement); XCTAssertEqual(afterFirst, "  - a\n- 😀 b\n- c"); let selection = NSRange(location: 0, length: ("  - a\n  - 😀 b" as NSString).length); let multi = MarkdownEditing.listIndentEdit(document: "  - a\n  - 😀 b\n- c", selection: selection, outdent: true)!; let restored = ("  - a\n  - 😀 b\n- c" as NSString).replacingCharacters(in: multi.range, with: multi.replacement); XCTAssertEqual(restored, document) }
    func testTabAfterEmptyBulletContinuationUsesWholeMarkerLine() { let document = "- \n- next"; let edit = MarkdownEditing.listIndentEdit(document: document, selection: NSRange(location: 2, length: 0), outdent: false)!; XCTAssertEqual((document as NSString).replacingCharacters(in: edit.range, with: edit.replacement), "  - \n- next") }
}
